//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public tblItem()
        {
            this.tblRightPages = new HashSet<tblRightPage>();
        }
    
        public int ItemId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> IsPicked { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> InventoryId { get; set; }
    
        public virtual tblInventory tblInventory { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual ICollection<tblRightPage> tblRightPages { get; set; }
    }
}
