//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblInventory
    {
        public tblInventory()
        {
            this.tblItems = new HashSet<tblItem>();
            this.tblLeftPages = new HashSet<tblLeftPage>();
        }
    
        public int InventoryId { get; set; }
        [Required(ErrorMessage="Article name is required.")]
        public string InventoryName { get; set; }
        public string InventoryDescription { get; set; }
        public string InventoryPicturePath { get; set; }
    
        public virtual ICollection<tblItem> tblItems { get; set; }
        public virtual ICollection<tblLeftPage> tblLeftPages { get; set; }
    }
}
