//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeftPage
    {
        public tblLeftPage()
        {
            this.tblRightPages = new HashSet<tblRightPage>();
        }
    
        public int PageId { get; set; }
        public string ReceiveingInfo { get; set; }
        public Nullable<int> ReceivingSerial { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public Nullable<int> PreviousBalance { get; set; }
        public Nullable<int> NoOfReceivingArticles { get; set; }
        public Nullable<int> TotalBalance { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> VoucharId { get; set; }
    
        public virtual tblInventory tblInventory { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual tblVouchar tblVouchar { get; set; }
        public virtual ICollection<tblRightPage> tblRightPages { get; set; }
    }
}
