//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public tblNotification()
        {
            this.tblRequisitionSlips = new HashSet<tblRequisitionSlip>();
        }
    
        public int NotificationId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public Nullable<System.DateTime> NotificationDate { get; set; }
        public string NotificationBody { get; set; }
        public Nullable<int> IsSeen { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual ICollection<tblRequisitionSlip> tblRequisitionSlips { get; set; }
    }
}
