//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRightPage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TakingDate { get; set; }
        public string WhereLocated { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RequisitionSerialNumber { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblLeftPage tblLeftPage { get; set; }
        public virtual tblRequisitionSlip tblRequisitionSlip { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
