//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string ReportTitle { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string ReportFilePath { get; set; }
    
        public virtual tblSector tblSector { get; set; }
    }
}
