//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblSector
    {
        public tblSector()
        {
            this.tblItems = new HashSet<tblItem>();
            this.tblLeftPages = new HashSet<tblLeftPage>();
            this.tblReports = new HashSet<tblReport>();
        }
    
        public int SectorId { get; set; }

        [Required(ErrorMessage="Name is required.")]
        public string SectorName { get; set; }

        public string SectorDescription { get; set; }

        public Nullable<System.DateTime> CreatingDate { get; set; }
    
        public virtual ICollection<tblItem> tblItems { get; set; }
        public virtual ICollection<tblLeftPage> tblLeftPages { get; set; }
        public virtual ICollection<tblReport> tblReports { get; set; }
    }
}
