//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblNotifications = new HashSet<tblNotification>();
            this.tblNotifications1 = new HashSet<tblNotification>();
            this.tblRequisitionSlips = new HashSet<tblRequisitionSlip>();
            this.tblRequisitionSlips1 = new HashSet<tblRequisitionSlip>();
            this.tblRequisitionSlips2 = new HashSet<tblRequisitionSlip>();
            this.tblRightPages = new HashSet<tblRightPage>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [DataType(DataType.Password)]
        [StringLength(10, MinimumLength = 5)]
        [Required()]
        public string Password { get; set; }
        public string JobPosition { get; set; }
        public Nullable<int> SystemPosition { get; set; }
        public string Sex { get; set; }
        public string PhotoPath { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string SignaturePath { get; set; }
    
        public virtual ICollection<tblNotification> tblNotifications { get; set; }
        public virtual ICollection<tblNotification> tblNotifications1 { get; set; }
        public virtual ICollection<tblRequisitionSlip> tblRequisitionSlips { get; set; }
        public virtual ICollection<tblRequisitionSlip> tblRequisitionSlips1 { get; set; }
        public virtual ICollection<tblRequisitionSlip> tblRequisitionSlips2 { get; set; }
        public virtual ICollection<tblRightPage> tblRightPages { get; set; }
    }
}
