//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_Final_Version2.Models.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVouchar
    {
        public tblVouchar()
        {
            this.tblLeftPages = new HashSet<tblLeftPage>();
        }
    
        public int VoucharId { get; set; }
        public string VoucharFilePath { get; set; }
    
        public virtual ICollection<tblLeftPage> tblLeftPages { get; set; }
    }
}
